# tag::adocProperties[]
quarkus.application.name=quarkus-app
quarkus.http.port=8701
quarkus.otel.metrics.enabled=true
quarkus.otel.logs.enabled=true
applicationinsights.connection.string=${APPLICATIONINSIGHTS_CONNECTION_STRING:}
# end::adocProperties[]

# tag::adocProdProperties[]
%prod.quarkus.datasource.username=postgres
%prod.quarkus.datasource.password=password
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
# end::adocProdProperties[]
