name: Build and deploy Micronaut native image

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/*.yml
      - micronaut-app/**
  workflow_dispatch:

permissions:
  contents: read

env:
  # Replace with your registry URL
  REGISTRY_URL: crjavaruntimessinedied.azurecr.io
  PROJECT: java-runtimes
  RESOURCE_GROUP: rg-java-runtimes

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: graalvm/setup-graalvm@0426e2e191540e8514dff98dc52a5f5146a2a276 # v1
        with:
          version: 'latest'
          java-version: '25'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to container registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build micronaut-app with GraalVM
        run: |
          cd micronaut-app && ./mvnw -Pnative native:compile
      - name: Build micronaut-app native Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          push: true
          tags: ${{ env.REGISTRY_URL }}/${{ env.PROJECT }}/micronaut-app-native:${{ github.sha }}
          file: ./micronaut-app/src/main/docker/Dockerfile.native
          context: ./micronaut-app/
      - name: Azure Login
        uses: azure/login@7184910d9eb2b1c5e48f7073824a90609bb9b6d6 # v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy micronaut-app native Docker image to Azure Container Apps
        uses: azure/CLI@9f7ce6f37c31b777ec6c6b6d1dfe7db79f497956 # v2
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            
            az containerapp update \
              --name micronaut-app \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --image ${{ env.REGISTRY_URL }}/${{ env.PROJECT }}/micronaut-app-native:${{ github.sha }} \
              --query "properties.configuration.ingress.fqdn" \
              --output tsv
